### ISSUE TITLE
Add links to buttons - fixed button at bottom

### ISSUE THREAD

**Issue by lawlere** [lawlere/portfolio_2015#11]
![screen shot 2015-08-04 at 9 40 45 pm](https://cloud.githubusercontent.com/assets/2300902/9078358/cb4125f6-3af1-11e5-86c4-352737d8a5c0.png)
FITSTAR: "Go to the FitStar Website" - http://fitstar.com/
KUBMO: "Go to the Kubmo website" - http://www.kubmo.builders/
GLASSBREAKERS: "Go to the Glassbreakers website" - https://www.glassbreakers.co/

**Comment by philipithomas** [comment]
What's the text size on this supposed to be @lawlere ?

**Comment by philipithomas** [comment]
Making the background color #15E2C4 - @lawlere let me know if wrong
