### ISSUE TITLE
slide navigator

### ISSUE THREAD

**Issue by lawlere** [lawlere/portfolio_2015#12]
Create slide navigator under each of the project tabs.

Include arrow right on the first page, and arrows right and left on the following pages. The right arrow on the last page will lead back to the first slide. The arrows should be fixed in the middle of the vertical height when the user scrolls past the initial arrow. 

Include pagination dots for each of the scroll pages. 3-5 for each project section.

At full width, the content is at 80% width, a smaller container than the project image squares. The user can either click the arrow to navigate through, or arrow right and left.

At 750 px, the images go full width and should be swipeable on mobile (no more arrows necessary
![screen shot 2015-08-04 at 9 52 04 pm](https://cloud.githubusercontent.com/assets/2300902/9078455/79e9834a-3af3-11e5-8895-2df8e5ebe79d.png)
).

**Comment by philipithomas** [comment]
According to @lawlere, this is no longer necessary
