### ISSUE TITLE
scrolling nav bar

### ISSUE THREAD

**Issue by lawlere** [lawlere/portfolio_2015#16]
[priority = low]

When user scrolls past top section, the nav bar slides in from the top of the browser. It shows the mermaid logo, and the 3 contact icons. Twitter and Linkedin icons should lead to a separate browser window. The email icon should open a new mail window with the email address filled in. The mermaid icon should scroll the user back to the top of the page.
![scroll_nav](https://cloud.githubusercontent.com/assets/2300902/9078667/33330996-3af6-11e5-8f3f-505e43090c7f.png)

**Comment by philipithomas** [comment]
@lawlere What do you define as "top section"? After the bay image background? Maybe 60% through that?
