### ISSUE TITLE
project secion - mobile

### ISSUE THREAD

**Issue by lawlere** [lawlere/portfolio_2015#18]
The project sections should go full screen, and stack on mobile. They should show down arrows, and all content should be collapsed until the user taps. Once the user taps on the tile, the content should collapse down, and the tile should change to an "x".
![fitstar_close](https://cloud.githubusercontent.com/assets/2300902/9078803/f1bdece0-3af7-11e5-9293-f8cde9799ed5.png)
![fitstar_down](https://cloud.githubusercontent.com/assets/2300902/9078799/f1bb5070-3af7-11e5-8e97-54a5c99c04cc.png)
![gb_close](https://cloud.githubusercontent.com/assets/2300902/9078800/f1bb6cfe-3af7-11e5-9e7f-0ad6b5dfb9ff.png)
![gb_down](https://cloud.githubusercontent.com/assets/2300902/9078801/f1bb93a0-3af7-11e5-8b5f-26b5a0e2abe7.png)
![kubmo_close](https://cloud.githubusercontent.com/assets/2300902/9078802/f1bc0268-3af7-11e5-8574-a8ac56229e13.png)
![kubmo_down](https://cloud.githubusercontent.com/assets/2300902/9078804/f1bec61a-3af7-11e5-8ce7-9716f0b962c8.png)

**Comment by philipithomas** [comment]
When you scroll to the bottom, unopened tiles are available to click on

**Comment by philipithomas** [comment]
@lawlere we have to discuss how to implement this before I can work on it.

**Comment by philipithomas** [comment]
Also, on click - should it scroll down to the content?

**Comment by lawlere** [comment]
Now you know

**Comment by lawlere** [comment]
![mobile_expand](https://cloud.githubusercontent.com/assets/2300902/9753450/cac16d98-5671-11e5-9d42-3198d3323c59.png)
