### ISSUE TITLE
Mobile section content

### ISSUE THREAD

**Issue by lawlere** [lawlere/portfolio_2015#19]
The content under each section should collapse down when the user taps on a tile. 

content width: 90%

button should go full width - look like a band. 
![screen shot 2015-08-04 at 10 29 55 pm](https://cloud.githubusercontent.com/assets/2300902/9078869/a636ebcc-3af8-11e5-83df-26d17e57bd4c.png)

**Comment by philipithomas** [comment]
@lawlere I think this may be done, at least on the code side. Can you confirm?
