### ISSUE TITLE
Implement a 404 page

### ISSUE THREAD

**Issue by philipithomas** [lawlere/portfolio_2015#29]
We need a page to show when somebody goes to a link that doesn't exist. I think something similar to your loading page would be cool, but we need to make sure it has a link back to the homepage.

**Comment by lawlere** [comment]
Just add copy to the load screen. With the "Emma Lawler" icon at the top, and text that says:

"You've arrived at Emma's website, but this page doesn't exist." <a>Go to the homepage</a>

**Comment by philipithomas** [comment]
"Go to homepage" is a button on a new line.
